apiVersion: apps/v1
kind: Deployment
metadata:
  name: rwanda-track-web-deployment
  namespace: blufountain-external
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rwanda-track-web
  template:
    metadata:
      labels:
        app: rwanda-track-web
    spec:
      containers:
      - name: rwanda-track-web-container
        image: kaributechsworkflow/rwanda-track-web:7fa59e96d588121883b96a175d8234f29fe0ec7c
        ports:
        - containerPort: 443
